import Head from 'next/head';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import SearchBar from '@/components/SearchBar/SearchBar';
import SecondaryButton from '@/components/secondaryButton/SecondaryButton';
import SwiperBtns from '@/components/SwiperBtns/SwiperBtns';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>AdBaazar</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <main
        style={{
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <SearchBar />
        <SwiperBtns />
        <SecondaryButton
          text={"Shop by Category"}
          type={"button"}
          style={{ width: "358px" }}
        />
        <Link href='/login'>Sign in</Link>
        <Link href='/register'>Sing up</Link>
        <Link href='/account'>Personal account</Link>
      </main>
    </>
  );
}
