import Head from "next/head";
import { useRouter } from "next/router";
import Layout from "@/components/Layout/Layout";
import SearchBar from "@/components/SearchBar/SearchBar";
import SecondaryButton from "@/components/secondaryButton/SecondaryButton";
import SwiperBtns from "@/components/SwiperBtns/SwiperBtns";
import {
  SectionHero,
  TextHero,
  HeroStar,
  HalfStarDark,
  NewestStar,
  DarkBg,
  DarkBgChil,
  ChildrenStar,
  DarkBgUsed,
 UsedStar,
} from "@/styles/index.styled";
import BookSectionLayout from "@/components/BookSectionLayout/BookSectionLayout";
import { sectionTexts } from "@/data/section-text";
import { BannerBestsellers, BannerChildren, BannerNewest, BannerSeller, BannerUsed } from "../../public/png/banners";
import BecomeSeller from "@/components/BecomeSeller/BecomeSeller";
import Subscription from "@/components/Subscribtion/Subscription";
import TopBookSellersSection from "@/components/TopBooksellersSection/TopBookSellersSection";
import { ToastContainer } from "react-toastify";
import { BgFull } from "../../public/backgrounds";
import { selectShowStars } from "@/redux/selectors";
import { useSelector } from "react-redux";

export default function Home() {
  const router = useRouter();
  const starVisibility = useSelector(selectShowStars);

  return (
    <>
      <Head>
        <title>AdBaazar</title>
        <meta name='description' content='Generated by create next app' />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1 minimum-scale=1, maximum-scale=1'
        />
      </Head>
      <main>
        <Layout>
          <SectionHero>
            <TextHero>find your favorite book</TextHero>
            <HeroStar src={BgFull} alt='star' />
            {starVisibility && <HalfStarDark src={BgFull} alt='star' />}
            {starVisibility && <DarkBg></DarkBg>}
            <SearchBar />
            <SwiperBtns />
            <SecondaryButton
              onClick={() => router.push("/categories")}
              text={"Shop by Category"}
              type={"button"}
              style={{ width: "358px", position: "absolute", zIndex: 3 }}
            />
          </SectionHero>
          <BookSectionLayout
            title={sectionTexts[0].title}
            text={sectionTexts[0].text}
            banner={BannerBestsellers}
            id={"bestsellers"}
          />
          <NewestStar src={BgFull} alt='star' />
          <BookSectionLayout
            title={sectionTexts[1].title}
            text={sectionTexts[1].text}
            banner={BannerNewest}
            id={"new"}
          />
          {starVisibility && <ChildrenStar src={BgFull} alt='star' />}
          {starVisibility && <DarkBgChil></DarkBgChil>}
          <BookSectionLayout
            title={sectionTexts[2].title}
            text={sectionTexts[2].text}
            banner={BannerChildren}
            id={"children"}
          />
          <Subscription />
          <BookSectionLayout
            title={sectionTexts[3].title}
            text={sectionTexts[3].text}
            banner={BannerUsed}
            id={"used"}
          />
          {starVisibility && <UsedStar src={BgFull} alt='star' />}
          {starVisibility && <DarkBgUsed></DarkBgUsed>}
          <TopBookSellersSection />
          <BecomeSeller />
          <BookSectionLayout
            title={sectionTexts[5].title}
            text={sectionTexts[5].text}
            banner={BannerSeller}
            id={"sale"}
          />
          <div style={{ color: "white", fontSize: "26px", height: "447px" }}>
            Popular authors & series in progress
          </div>
          <ToastContainer />
        </Layout>
      </main>
    </>
  );
}
