export { default as AddBook } from './AddBook/AddBookTab';
export { default as Payments } from './Payments/Payments';
export { default as Settings } from './Settings/Settings';
export { default as Support } from './Support/Support';
export { default as Favorites } from './Favorites/Favorites';
export { default as PersonalInfo } from './PersonalInfo/PersonalInfo';
export { default as OrderHistory } from './OrderHistory/OrderHistory';
export { default as Comments } from './Comments/Comments';
export { default as Notifications } from "./Notifications/Notifications";
